### PR TITLE
REST v1.1

### PR DESCRIPTION
**Pull request by AnkurGel**
Instamojo API has been [updated to v1.1](https://www.instamojo.com/developers/rest/). 
With the new API, several new features: 
- [x] Optional parameter to provide dev `auth_token` to play around with API directly.
- [x] `Offer` terminology has been shifted to `Link`
- [x] Add `file_upload` and `cover_image` support in wrapper.
- Payment API introduction: 
  - [x] List of payments
  - [x] Requesting new payment
  - [x] Details and status of payment(s)
- Refund API introduction
  - [x] List of refunds
  - [x] Create a refund
  - [x] Details of a refund
- [x] Endpoint for test api.
- [x] Update README
- [x] Publish on [RubyGems](https://rubygems.org/gems/Instamojo-rb)

Development of following is being carried out in branch [1.1](https://github.com/AnkurGel/Instamojo-rb/tree/1.1)
Closing issue #1

### CODE REVIEW

**Comment by AnkurGel** [comment]
@ashwch Updated with the refund API. Let me know if you require the bundled gem to test.

**Comment by ashwch** [comment]
@AnkurGel Great! I have [opened a PR](https://github.com/AnkurGel/Instamojo-rb/pull/3) against your 1.1 branch, after those changes it is good to go.

One more thing, if it is possible to make the base API URL an optional argument to `Instamojo::API.new()` then it would be useful for users to provide different URL on the fly. For example we also have `https://test.instamojo.com/api/1.1` as well. The Python and PHP wrappers are already handling the same.

**Comment by AnkurGel** [comment]
Thanks @ashwch. Merged #3. Yes, adding an optional parameter to add test endpoint makes sense. I have pushed the support for that. Give it a shot, then we're set for release. :smile:

**Comment by AnkurGel** [comment]
@ashwch - Hey. Merged #4. Cleaned up some code. Can you please check if it all works good for you for v1.1?

**Comment by AnkurGel** [comment]
Also, according to [documentation](https://www.instamojo.com/developers/rest/#toc-refunds), a created refund can only be retrieved by `/refunds/:refund_id`. While this is good, it would be awesome to have this RESTful GET route on payments - `/payments/:payment_id/refund`, if possible. I just added [`#process_refund`](https://github.com/AnkurGel/Instamojo-rb/commit/110342d6c50606122b5b471fab3d37982bfc4c07) in `Payment` class which helps to instantaneously process refund for a given payment. Exposing that additional route will enable me to check and get the existing refund carried on that payment(`payment.get_refund`).  // cc @ashwch

**Comment by AnkurGel** [comment]
bump! // cc @ashwch

**Comment by ashwch** [comment]
@AnkurGel Apologies, been bust lately. Regarding `payments/:payment_id/refund`, it's a good point, but we won't be able to change the endpoints now.

I will try to test the new changes by EOD.

**Comment by AnkurGel** [comment]
Cool. No problem.

On Thu, Dec 17, 2015 at 12:20 PM, Ashwini Chaudhary <
notifications@github.com> wrote:

> @AnkurGel https://github.com/AnkurGel Apologies, been bust lately.
> Regarding payments/:payment_id/refund, it's a good point, but we won't be
> able to change the endpoints now.
> 
> I will try to test the new changes by EOD.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AnkurGel/Instamojo-rb/pull/2#issuecomment-165358292.

## 

-Ankur Goel

**Comment by ashwch** [comment]
@AnkurGel Added 2 comments. After those minor changes we can publish it on RubyGems. Big thanks !-)

**Comment by AnkurGel** [comment]
@ashwch : Awesome. Thanks a lot for help and contribution! Fixed doc. 
And here we go - https://rubygems.org/gems/Instamojo-rb.
If you'd like, you can keep a forked copy of this repo in Instamojo org and add the gem in [supported libraries](https://www.instamojo.com/beta/integrations). 
Spread the word :)

**Pull request merged**
